voyager-hilt/src/main/java/cafe/adriel/voyager/hilt/ViewModel.kt, voyager-hilt/src/main/java/cafe/adriel/voyager/hilt/VoyagerHiltViewModelFactories.kt, voyager-hilt/src/main/java/cafe/adriel/voyager/hilt/internal/ContextExt.kt
Default ViewModelFactory provided by Hilt was using your own StateProviderOwner instead of `AndroidScreenLifecycleOwner`. So keys were kept in the activity owner and the instance in the `AndroidScreenLifecycleOwner`.
Behavior reported here: #20
=> fix: SavedStateProvider with the given key is already registered

gradle/wrapper/gradle-wrapper.properties, voyager-bottom-sheet-navigator/build.gradle.kts, voyager-core/build.gradle.kts, voyager-kodein/build.gradle.kts, voyager-navigator/build.gradle.kts, voyager-tab-navigator/build.gradle.kts, voyager-transitions/build.gradle.kts
This PR fixes the issue from the #34 by removing Jetbrains Compose transitive dependencies on all targets.
=> fix: Jetbrains Compose transitive dependencies on Android projects

samples/multiplatform/build.gradle.kts, voyager-androidx/src/main/java/cafe/adriel/voyager/androidx/AndroidScreenLifecycleOwner.kt, voyager-core/src/commonMain/kotlin/cafe/adriel/voyager/core/lifecycle/ScreenLifecycleHooks.kt, voyager-core/src/commonMain/kotlin/cafe/adriel/voyager/core/lifecycle/ScreenLifecycleOwner.kt, voyager-core/src/commonMain/kotlin/cafe/adriel/voyager/core/lifecycle/ScreenLifecycleStore.kt, voyager-navigator/src/commonMain/kotlin/cafe/adriel/voyager/navigator/Navigator.kt, voyager-navigator/src/commonMain/kotlin/cafe/adriel/voyager/navigator/internal/NavigatorDisposable.kt
This fix is because Navigator dispose checks the last disposed or replaced screen. But first navigator screen will be never popped or replaced because Navigator needs at least one screen to work. Pressing back button or closing applications never dispose first screen.
So here we are putting a effect to dispose based on Navigator been replaced or application been finished. And if a Navigator is totally replaced by another (yes, we can't avoid users does that) it'll will dispose all pushed screens.
=> fix: initial screen and its model not disposing

buildSrc/src/main/kotlin/Setup.kt
To increase the library compatibility with other projects, we should target java 8 for bytecode compatibility compilation.
=> Downgrade jvmTarget to Java 1.8 for compatibility

voyager-androidx/src/main/java/cafe/adriel/voyager/androidx/AndroidScreenLifecycleOwner.kt, voyager-core/src/commonMain/kotlin/cafe/adriel/voyager/core/lifecycle/ScreenLifecycleOwner.kt, voyager-navigator/src/commonMain/kotlin/cafe/adriel/voyager/navigator/Navigator.kt, voyager-navigator/src/commonMain/kotlin/cafe/adriel/voyager/navigator/internal/NavigatorDisposable.kt
Closes #42
Closes #79
Handle Lifecycle.Event instead of managing the states themselves, include a onStart and onStop function to say when the screen is displayed.
Note that this fix is included in my fork of Voyager https://github.com/Syer10/voyager
=> Fix Lifecycle issues

voyager-navigator/src/commonMain/kotlin/cafe/adriel/voyager/navigator/internal/NavigatorDisposable.kt
Closes #86
Handle multiple screen popping and replacing not disposing ScreenModels and such.
Note that this fix is included in my fork of Voyager https://github.com/Syer10/voyager
=> Support multiple screen popping and replacing

voyager-core/src/commonMain/kotlin/cafe/adriel/voyager/core/stack/SnapshotStateStack.kt, voyager-core/src/commonMain/kotlin/cafe/adriel/voyager/core/stack/Stack.kt
creates `replaceAll(items: List<Item>)` allowing a step to replace the navigation stack with another stack
=> Add replaceAll overload to allow replacing a stack with another

voyager-bottom-sheet-navigator/src/commonMain/kotlin/cafe/adriel/voyager/navigator/bottomSheet/BottomSheetNavigator.kt
Closes #122 
Adds `skipHalfExpanded` in the parameters to enable bottom sheet to show in full mode.
=> Added support to expand skip half expanded mode

gradle/libs.versions.toml, voyager-kodein/build.gradle.kts
Now that the [multiplatform branch for kmm on kodein](https://github.com/kosi-libs/Kodein/pull/431) is merged and release on the `version 7.19.0`, I decided to bump the version to the `7.20.1` and make the kodein wrapper compatible.
=> Updated kodein and changed the module multoplatform flag

voyager-core/src/commonMain/kotlin/cafe/adriel/voyager/core/model/ScreenModel.kt
There is no need to do unnecessary dispatching using `Dispatchers.Main` since ScreenModel's operations are intended to run immediately on the main thread, this matches what [AndroidX ViewModel](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:lifecycle/lifecycle-viewmodel-ktx/src/main/java/androidx/lifecycle/ViewModel.kt;l=35?q=viewModelScope&sq=&ss=androidx%2Fplatform%2Fframeworks%2Fsupport) is doing for `viewModelScope` property. 
Also, `Dispatcher.Main.immediate` is available on Android, Apple platforms, Web (JS), JavaFX(Desktop). So, it should be safe to use it in the `commonMain`
=> Use `Dispatchers.Main.immediate` instead of `Dispatchers.Main` for ScreenModel's `coroutineScope`

voyager-bottom-sheet-navigator/src/commonMain/kotlin/cafe/adriel/voyager/navigator/bottomSheet/BottomSheetNavigator.kt
Fixes #203
Fixes #221 
`isVisible` is `false` when we click outside the bottom sheet so it is not being removed from the stack.
This happens because we are NOT vetoing bottom sheet state change so when it arrives in Voyager's `hide()` is already hiding. This is the solution for now, before the release I will look into this veto issue.
**To reproduce**
1. Run `samples:android` and click "Bottom Sheet Navigation" button;
2. Open logs, `BasicNavigationScreen` has a `LifecycleEffect` that logs onStarted/onDisposed.
3. Click "Show BottomSheet"
3.1. **Swipe down**: hidden, disposed and replaced by HiddenBottomSheet
3.2. **Add a button** inside `BasicNavigationScreen` **that calls** `bottomSheetNavigator.hide()`, click on it: hidden, disposed and replaced by HiddenBottomSheet
3.2. **Click …
=> Fix bottom sheet dismiss on click outside issue

voyager-core/src/androidMain/kotlin/cafe/adriel/voyager/androidx/AndroidScreenLifecycleOwner.kt
fixes #225
fixes #186
fixes #173
=> fix: propagating lifecycle events to AndroidScreenLifecycleOwner

voyager-core/src/commonMain/kotlin/cafe/adriel/voyager/core/model/ScreenModel.kt, voyager-core/src/commonMain/kotlin/cafe/adriel/voyager/core/model/ScreenModelStore.kt, voyager-navigator/src/commonMain/kotlin/cafe/adriel/voyager/navigator/Navigator.kt
This PR is a proposal to remove all extensions APIs (in this case ScreenModel API) from the `dispose` function of the Navigator, there is no need for it currently, it can be replaced with `ScreenLifecycleStore`.
This will decouple the Navigator of the Screen Model API.
=> refactor: removing the directly dispose of ModelStore and replace with Screen Lifecycle API

voyager-core/src/commonMain/kotlin/cafe/adriel/voyager/core/model/ScreenModelStore.kt, voyager-hilt/build.gradle.kts, voyager-hilt/src/main/java/cafe/adriel/voyager/hilt/ScreenModel.kt, voyager-kodein/build.gradle.kts, voyager-kodein/src/commonMain/kotlin/cafe/adriel/voyager/kodein/ScreenModel.kt, voyager-koin/build.gradle.kts, voyager-koin/src/commonMain/kotlin/cafe/adriel/voyager/koin/ScreenModel.kt, voyager-navigator/src/commonMain/kotlin/cafe/adriel/voyager/navigator/screenModel/NavigatorScreenModel.kt
Proposal API for `ScreenModel` scoped in Navigator.  This implementation follows the current ScreenModelStore implementation, and it supports on it for Navigator ScreenModel, the custom dependencies API works as expected as well for Navigator Scoped.
Usage:
```kotlin
val navigator = LocalNavigator.currentOrThrow
val screenModel = navigator.rememberNavigatorScreenModel { YourScreenModel() }
```
For Root Navigator
```kotlin
val navigator = LocalNavigator.currentOrThrow
val rootNavigator = remember(navigator) { navigator.root() }
val screenModel = rootNavigator.rememberNavigatorScreenModel { YourScreenModel() }
fun Navigator.root(): Navigator {
return if(parent == null) this
else parent!!.root()
}
```
https://github.com/adrielcafe/voyager/assets/29736164/dc19d34e-0273-430b-95b6-08a0f09a923b …
=> Navigator scoped ScreenModel

gradle/libs.versions.toml, samples/multiplatform/build.gradle.kts, voyager-core/build.gradle.kts, voyager-core/src/androidMain/kotlin/cafe/adriel/voyager/core/concurrent/PlatformDispatcher.android.kt, voyager-core/src/commonMain/kotlin/cafe/adriel/voyager/core/concurrent/PlatformDispatcher.kt, voyager-core/src/commonMain/kotlin/cafe/adriel/voyager/core/model/ScreenModel.kt, voyager-core/src/desktopMain/kotlin/cafe/adriel/voyager/core/concurrent/PlatformDispatcher.desktop.kt, voyager-core/src/jsMain/kotlin/cafe.adriel.voyager.core/concurrent/PlatformDispatcher.js.kt, voyager-core/src/nativeMain/kotlin/cafe.adriel.voyager.core/concurrent/PlatformDispatcher.native.kt, voyager-koin/build.gradle.kts
This adds ScreenModel `screenModelScope` Dispatcher per Platform.
Fixes: #240
Also document Desktop used: https://voyager.adriel.cafe/screenmodel/coroutines-integration#desktop-note
=> feat: platform dispatchers

voyager-core/src/androidMain/kotlin/cafe/adriel/voyager/androidx/AndroidScreenLifecycleOwner.kt
=> fix: event emit on destroy state #280

voyager-transitions/src/commonMain/kotlin/cafe/adriel/voyager/transitions/CrossfadeTransition.kt
This PR adds a basic crossfade transition for navigation, as I felt it's missing.
=> Add crossfade transition

voyager-navigator/api/android/voyager-navigator.api, voyager-navigator/api/desktop/voyager-navigator.api, voyager-navigator/src/androidMain/kotlin/cafe/adriel/voyager/navigator/internal/Actuals.kt, voyager-navigator/src/commonMain/kotlin/cafe/adriel/voyager/navigator/internal/NavigatorBackHandler.kt, voyager-navigator/src/commonWebMain/kotlin/cafe/adriel/voyager/navigator/internal/Actuals.web.kt, voyager-navigator/src/desktopMain/kotlin/cafe/adriel/voyager/navigator/internal/Actuals.kt, voyager-navigator/src/iosMain/kotlin/cafe.adriel.voyager.navigator.internal/Actuals.uikit.kt, voyager-navigator/src/macosMain/kotlin/cafe.adriel.voyager.navigator.internal/Actuals.macos.kt
Makes the BackHandler a internal public API.
=> Make BackHandler a internal public api

voyager-bottom-sheet-navigator/src/commonMain/kotlin/cafe/adriel/voyager/navigator/bottomSheet/BottomSheetNavigator.kt
Issue details:
https://github.com/adrielcafe/voyager/issues/330
Affected Platform: iOS
Compose version: 1.6.0
It seems the culprit is `confirmValueChange` in `rememberModalBottomSheetState`, it's using `rememberSaveable` where `confirmValueChange` is used as a key. When this method changes in iOS somehow when you open keyboard or any other thing that causes recomposition, it recreates the sheet state, which hides the bottom sheet modal.
Removing `confirmValueChange` and using `LaunchedEffect` to observe `sheetState.currentValue` solves the issue.
=> Fix: BottomSheet closes when recomposing in iOS #330

voyager-core/src/androidMain/kotlin/cafe/adriel/voyager/androidx/AndroidScreenLifecycleOwner.kt
In continuation to this PR
https://github.com/adrielcafe/voyager/pull/415
I think this solution is better and i also checked it in our project
I don't actually see where `onDispose` in `AndroidScreenLifecycleOwner` would be called when configuration changes. And I think it's the client of `AndroidScreenLifecycleOwner` responsibility to decide when to dispose it
@DevSrSouza what to you think?
=> second way to fix activity leak after configuration change

samples/android/src/main/java/cafe/adriel/voyager/sample/basicNavigation/BasicNavigationScreen.kt, voyager-core/src/commonMain/kotlin/cafe/adriel/voyager/core/lifecycle/LifecycleEffectStore.kt, voyager-core/src/commonMain/kotlin/cafe/adriel/voyager/core/lifecycle/ScreenLifecycle.kt
This adds to possibility to run a sync block of code, only on the first time the screen appears.
Usage:
```kotlin
LifecycleEffectOnce {
myScreenModel.initSomething()
}
```
=> Lifecycle Effect Once API

voyager-lifecycle-kmp/src/androidMain/kotlin/cafe/adriel/voyager/jetpack/AndroidScreenLifecycleOwner.android.kt
Currently, there are two `LocalLifecycleOwner` in `cmp 1.6.10` (1.7.0+ will resolved it):
- `androidx.compose.ui.platform.LocalLifecycleOwner`
- `androidx.lifecycle.compose.LocalLifecycleOwner`
As per jetbrains's [suggestion](https://github.com/JetBrains/compose-multiplatform-core/blob/8f929c7251081e3db77dc0f0d1197ab8e2628940/lifecycle/lifecycle-runtime-compose/src/commonMain/kotlin/androidx/lifecycle/compose/LocalLifecycleOwner.kt#L28):
```kotlin
// androidx.lifecycle.compose.LocalLifecycleOwner.kt
Note: On Android, it works only with Compose UI 1.7.0-alpha05 or above.
*  Please use [androidx.compose.ui.platform.LocalLifecycleOwner] on Compose 1.6.*
```
In the cmp code, wo can find that two `LocalLifecycleOwner` are the same without `androidTarget`. …
=> provide androidx.lifecycle.compose.LocalLifecycleOwner in android target

samples/android/src/main/java/cafe/adriel/voyager/sample/screenTransition/SampleScreens.kt, samples/android/src/main/java/cafe/adriel/voyager/sample/screenTransition/SampleTransitions.kt, samples/android/src/main/java/cafe/adriel/voyager/sample/screenTransition/ScreenTransitionActivity.kt, voyager-transitions/api/android/voyager-transitions.api, voyager-transitions/api/desktop/voyager-transitions.api, voyager-transitions/src/commonMain/kotlin/cafe/adriel/voyager/transitions/FadeTransition.kt, voyager-transitions/src/commonMain/kotlin/cafe/adriel/voyager/transitions/ScaleTransition.kt, voyager-transitions/src/commonMain/kotlin/cafe/adriel/voyager/transitions/ScreenTransition.kt, voyager-transitions/src/commonMain/kotlin/cafe/adriel/voyager/transitions/SlideTransition.kt
To implement an animation such as the following, we need to use the zindex value.
<image src="https://github.com/adrielcafe/voyager/assets/17807925/589e79a2-1d96-44bd-bfc8-67c5036d2a78" width="200"/>
=> Support zIndex Config for Transition

docs/navigation/tab-navigation.md
Just noticed some grammatical errors in this documentation so I decided to fix it :)
=> Fixed some grammatical errors in tab-navigation.md
